# site settings
title: rbrtsmith
email: robert@rbrtsmith.com
description: "I write about Front End Development"
baseurl: ""
#uel: "http//rbrtsmith.com"
timezone: Europe/Stockholm

# Build settings
markdown: kramdown
permalink: /:year/:month/:title
paginate: 10

exclude: ["package.json", "Gruntfile.js", "node_modules", "js/source", "img/source"]