# site settings
title: rbrtsmith
email: robert@rbrtsmith.com
description: "Articles on CSS, JavaScript, front-end developent, and website performance."
baseurl: ""
url: "http://rbrtsmith.com"
timezone: Europe/Stockholm

gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
permalink: /:year/:month/:title
paginate: 5

exclude: [
	package.json,
	Gruntfile.js,
	node_modules,
	js/source,
	img/source,
	.git,
	.gitignore,
	.sass-cache,
	README.md,
	.DS_STORE,
	CNAME,
	img/source,
	js/source,
	css/scss]

# _layouts/compress.html
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
